// ============================================================================
// Library Exports - Central export point for all lib utilities
// ============================================================================

// API client and helpers
export {
  api,
  createApiClient,
  createAuthenticatedClient,
  createQueryString,
  parseQueryString,
  encodeParams,
  decodeParams,
  isSuccess,
  isError,
  unwrap,
  unwrapOr,
  type ApiResponse,
  type ApiError,
  type RequestConfig,
} from './api';

// Crypto utilities
export {
  hashString,
  hashData,
  createDeterministicId,
  hashEthereumMessage,
  isValidAddress,
  toChecksumAddress,
  hasValidChecksum,
  shortenAddress,
  addressesEqual,
  splitSignature,
  joinSignature,
  recoverSigner,
  verifySignature,
  randomBytes,
  randomHex,
  randomId,
  randomNonce,
  stringToHex,
  hexToString,
  bytesToBase64,
  base64ToBytes,
  createTipStreamDomain,
  TIP_MESSAGE_TYPES,
  SUBSCRIPTION_MESSAGE_TYPES,
  createMerkleLeaf,
  hashMerkleNodes,
  buildMerkleTree,
  getMerkleRoot,
  getMerkleProof,
  verifyMerkleProof,
  type SignatureComponents,
  type TypedDataDomain,
} from './crypto';

// Storage utilities
export {
  isStorageAvailable,
  setItem,
  getItem,
  removeItem,
  clearStorage,
  clearExpired,
  STORAGE_KEYS,
  createStorageKey,
  themeStorage,
  settingsStorage,
  draftTipStorage,
  visitStorage,
  onStorageChange,
  onKeyChange,
  getStorageSize,
  getStorageQuota,
  exportStorage,
  importStorage,
  type StorageKeyConfig,
  type StorageType,
} from './storage';

// Analytics utilities
export {
  getAnalytics,
  initAnalytics,
  trackPageView,
  trackWalletConnect,
  trackWalletDisconnect,
  trackTipSent,
  trackTipReceived,
  trackSubscription,
  trackNFTMint,
  trackCheckIn,
  trackFeatureUsage,
  trackError,
  trackButtonClick,
  trackFormSubmit,
  trackSearch,
  trackShare,
  trackTiming,
  measureDuration,
  type AnalyticsEvent,
  type UserProperties,
  type AnalyticsConfig,
} from './analytics';

// Date utilities
export {
  formatRelativeTime,
  formatFutureTime,
  formatShortDate,
  formatFullDate,
  formatISODate,
  formatTime,
  formatDateTime,
  formatTimestamp,
  formatDuration,
  formatDurationDays,
  formatCountdown,
  startOfDay,
  endOfDay,
  startOfWeek,
  startOfMonth,
  addDays,
  addHours,
  addMinutes,
  subtractDays,
  isToday,
  isYesterday,
  isPast,
  isFuture,
  isSameDay,
  diffInDays,
  fromUnixTime,
  toUnixTime,
  getDeadline,
  formatBlockchainTime,
  hasExpired,
  getTimeRemaining,
  formatTimeRemaining,
} from './date';

// Validation utilities
export {
  required,
  minLength,
  maxLength,
  pattern,
  min,
  max,
  ethereumAddress,
  notZeroAddress,
  isValidEthAmount,
  ethAmount,
  withinBalance,
  minTipAmount,
  tipMessage,
  noProfanity,
  isValidUrl,
  url,
  httpsUrl,
  isValidEmail,
  email,
  username,
  validate,
  createValidator,
  validateForm,
  validateTipForm,
  validateSubscriptionForm,
  validateCreatorProfile,
  type ValidationResult,
  type ValidationRule,
  type ValidatorConfig,
} from './validation';

// Error handling utilities
export {
  AppError,
  WalletError,
  TransactionError,
  ValidationError,
  NetworkError,
  ContractError,
  RateLimitError,
  ErrorCodes,
  ErrorMessages,
  parseWeb3Error,
  parseApiError,
  tryCatch,
  tryCatchSync,
  withRetry,
  withTimeout,
  logError,
  createErrorHandler,
  getUserFriendlyMessage,
  getDisplayError,
} from './errors';
